FROM node:16-buster

ARG UID
ENV UID=${UID:-1000}
ARG GID
ENV GID=${GID:-1000}

# Perform all OS package installation and cleanup in one single command to reduce the
# size of the created layer.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    gnupg2 \
    dos2unix \
    tini \
    && apt-get autoclean \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# The node image already creates a non-root user to run as, update its ids so they
# match the provided UID and GID we wish to build and run this image with.
# If GID or UID already exist that's OK no need to stop the build.
RUN groupmod -g ${GID} node || exit 0
RUN usermod -u ${UID} -g ${GID} node || exit 0

USER $UID:$GID

# Create and install the dependencies in separate COPY commands
COPY --chown=$UID:$GID ./web-frontend/package.json ./web-frontend/yarn.lock /digit/web-frontend/

WORKDIR /digit/web-frontend

RUN yarn install

COPY --chown=$UID:$GID ./web-frontend /digit/web-frontend/

# Fix (local dev) proxy setting to forward all traffic to the right container
RUN sed -i 's/localhost:8000/backend:8000/g' /digit/web-frontend/package.json

RUN dos2unix /digit/web-frontend/docker/docker-entrypoint.sh && \
    chmod a+x /digit/web-frontend/docker/docker-entrypoint.sh

# tini installed above protects us from zombie processes and ensures the default signal
# handlers work, see https://github.com/krallin/tini.
ENTRYPOINT ["/usr/bin/tini", "--", "/bin/bash", "/digit/web-frontend/docker/docker-entrypoint.sh"]
CMD ["dev"]

