# Generated by Django 4.0.2 on 2022-02-08 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=1500)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accounts', models.ManyToManyField(related_name='sites', to='abb.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MotionAsset',
            fields=[
                ('motionAssetId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('assetId', models.CharField(max_length=50)),
                ('assetTypeId', models.CharField(max_length=50)),
                ('assetTypeVersion', models.CharField(max_length=50)),
                ('assetType', models.CharField(max_length=50)),
                ('assetFamily', models.CharField(max_length=50)),
                ('assetName', models.CharField(max_length=100)),
                ('baseAPI', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('organizationName', models.CharField(blank=True, max_length=100)),
                ('assetOwner', models.CharField(blank=True, max_length=100)),
                ('serialNumber', models.CharField(max_length=100)),
                ('assetGroupId', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='abb.site')),
            ],
        ),
        migrations.CreateModel(
            name='MotionAssetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('measurements', models.JSONField()),
                ('tvi', models.FloatField()),
                ('dvi', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='abb.motionasset')),
            ],
            options={
                'unique_together': {('asset', 'month', 'year')},
            },
        ),
    ]
