# Generated by Django 4.0.2 on 2022-02-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_alter_motionasset_assetfamily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionasset',
            name='assetOwner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motionasset',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
